### ISSUE TITLE
Fin TP1

### ISSUE THREAD

**Issue by maevatrivino** [PolytechLyon/2019-isi3-graph-trivino_philibert#14]
Nous avons terminé le TP1 ainsi que le rapport. Si nous pouvons avoir vos retours pour nous corriger. 
Merci d'avance.

**Comment by Slashgear** [comment]
- [ ] Il me manque l'UML dans la question 2
- Connaissez vous la programmation fonctionnelle ? 
Si non, vous verrez ça dans un TP prochainement
Si oui vous pouvez réécrire cette partie de code.
https://github.com/PolytechLyon/2019-isi3-graph-trivino_philibert/blob/9ddd4dd5fdc22808c2a9457bcb61f12f247e47a4/src/main/java/graph/Graph.java#L177-L211
- [ ] Pourquoi conserver des variables avec un `_` au début ? Est-ce nécessaire?Justifier
- [ ] Vous ne semblez pas trop avoir compris le pattern de l'itérateur.

https://github.com/PolytechLyon/2019-isi3-graph-trivino_philibert/blob/9ddd4dd5fdc22808c2a9457bcb61f12f247e47a4/src/main/java/graph/Graph.java#L96-L122

Vous cassez ici la règle "Single Responsability", votre classe génère un graph et ses parcours. 
Cela fait trop de responsabilité.

Résultat votre classe Graph fait 200 lignes. ⚠️ 

Essayer de créer des classes séparés pour vos itérateurs 

```java
class BFSIterator<Node> implement Iterator<Node> {
}
```

- [ ] Ne remarquez vous pas que l'algo BFS et DFS sont très proche ? Quelle règle n'est pas respectée ?

**Comment by maevatrivino** [comment]
Bonsoir,
Nous avons dans un premier temps rajouté l'UML dans la question 2 (les fonctions vont probablement bouger avant le rendu final).
Pour la programmation fonctionnelle, nous ne connaissions pas mais on c'est risqué de chercher sur internet et nous avons appliqué une modification en utilisant des variables _final_.
Nous avons enlever les _ aux variables, c'est expliqué dans le rapport.
Pour finir, le pattern itérateur, je crois qu'on est perdu, c'est que les créations d'itérateurs sont pas au bon endroit ou c'est uniquement l'ajout d'une classe qui manque ? (Ou peut être une autre raison qui nous échappe).

Merci d'avance.

**Comment by Slashgear** [comment]
Ici vous n'utilisez pas le pattern Iterator, vous construisez un liste a partir d'un arbre parcouru et vous retournez l'itérateur associé à cette liste.
Je vous demande de crée un Itérateur pour **votre** graph

**Comment by maevatrivino** [comment]
Nous avons poussé une nouvelle implémentation du pattern iterator.
Cela compte pour un deuxième rendu

**Comment by maevatrivino** [comment]
Bonjour,

N'ayant pas eu de réponse, je considère que le rendu est correct ?

**Comment by Slashgear** [comment]
Tu peux juste considérer que je n'ai pas eu le temps de repasser sur votre TP depuis. 
(Je priorise toujours les nouveaux TPs que je n'ai pas encore lu avant de passer sur ceux qui sont "remédiés", je fais ce que je peux pour corriger au fur et à mesure. Convenez que j'ai un travail et que je fais ça quand je peux)

# ℹ️ Un TP est terminé quand l'issue de rendu est clôturé.

Dans votre cas, le TP n'est pas terminé.

https://github.com/PolytechLyon/2019-isi3-graph-trivino_philibert/blob/88a52b0a09f84c1edf9c24d505ef09e0a2406111/src/main/java/graph/Graph.java#L93-L213

Plusieurs choses sur vos parcours:

- Ne remarquez vous pas que vos deux classes sont quasiment identique et brisent donc la règle **DRY** ?
- Ne remarquez vous pas que dans votre fonction `parcoursGraph` vous avez deux implémentations ? Cela brise la règle `Single responsability` (**S**OLID)
- Enfin, si on regarde les deux "algo" de parcours en reculant sa chaise de 50 centimètres, on peut remarquer que ceux-ci sont très proches dans leur implémentation.

Avant de l'implémenter, indiquer moi quelle stratégie nous pouvons employer pour corriger ces problèmes afin de mutualiser un maximum le code des deux algo ?

**Comment by maevatrivino** [comment]
Bonjour,

Pardon, j'attendrai votre réponse à l'avenir.

En ce qui concerne la modification de l'itérateur, nous allons en faire qu'un seul qui stockera un boolean pour savoir si le parcours est en largeur ou en profondeur.
Nous avons pensé pour l'algorithme de parcours que nous pouvions faire une ArrayList de Node.
On ajoute le premier node en paramètre et on le marque.
On parcours la liste du parcours et on regarde pour chacun ses nodes adjacents.
S'il en a et qu'ils sont pas marqué, ils sont : 
	- Ajoutés à la fin de la liste pour un parcours en largeur.
	- Ajoutés juste après le node que l'on observe pour un parcours en profondeur.
Après l'ajout de chacun des nodes adjacents, on les marque.
Ensuite on regarde le noeud suivant de la liste, jusqu'à la fin de la liste.
A la fin de l'algorithme, les nodes sont démarqués.

**Comment by Slashgear** [comment]
La solution du booléen est assez empirique, que se passe-t-il le jour quand tu aura un troisième algo de parcours à implémenter ?

**Comment by maevatrivino** [comment]
Effectivement, nous pensons peut être à un caractère voire même à une string pour être plus explicite.
Si effectivement le nouveau parcours ressemble fortement, nous pourrons ajouter une nouvelle condition sur l'algorithme du parcours. 
Cependant, si le parcours est vraiment différent, un nouvel algorithme pourrait être pensé. Cela implique un nouveau traitement au niveau du constructeur voir pourquoi pas devoir produire un nouvel iterateur si toutes les fonctions sont vraiment différentes.

**Comment by Slashgear** [comment]
Et si on utilisait la logique Objet plutôt que ces méthodes empiriques ?

**Comment by maevatrivino** [comment]
On crée un itérateur pour le parcours en largeur et un pour le parcours en profondeur et ceux-ci hérite de notre itérateur global ?

**Comment by Slashgear** [comment]
oui :)

**Comment by maevatrivino** [comment]
Je viens aussi de me rendre compte que mon algorithme avec les listes est peut être pas assez adaptée par rapport au système d'héritage et que je pourrais surcharger une méthode pour visiter mes nodes et ainsi simuler la file ou la pile.

**Comment by maevatrivino** [comment]
Nous avons implémenter les nouveaux itérateurs et le rapport est à jour.
